# Generated by Django 5.2 on 2025-05-29 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokewordle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokewordlehint',
            name='game',
        ),
        migrations.RenameField(
            model_name='pokewordlegame',
            old_name='is_finished',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='pokewordlegame',
            old_name='pokemon_to_guess',
            new_name='pokemon',
        ),
        migrations.AddField(
            model_name='pokewordlegame',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokewordlegame',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PokewordleGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_text', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='pokewordle.pokewordlegame')),
            ],
        ),
        migrations.DeleteModel(
            name='PokewordleAttempt',
        ),
        migrations.DeleteModel(
            name='PokewordleHint',
        ),
    ]
