# Generated by Django 5.2.1 on 2025-05-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokewordle', '0002_remove_pokewordlehint_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokewordleguess',
            name='game',
        ),
        migrations.DeleteModel(
            name='PokewordleGame',
        ),
        migrations.DeleteModel(
            name='PokewordleGuess',
        ),
    ]
