# Generated by Django 5.2.1 on 2025-05-28 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
        ('pokemon', '0002_remove_type_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comparison',
            new_name='Compare',
        ),
    ]
