# Generated by Django 5.2 on 2025-05-07 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('effect', models.TextField(blank=True, null=True, verbose_name='Efecto')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_id', models.PositiveIntegerField(unique=True, verbose_name='Pokédex ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('height', models.FloatField(verbose_name='Altura (dm)')),
                ('weight', models.FloatField(verbose_name='Peso (hg)')),
                ('hp', models.PositiveIntegerField(verbose_name='PS')),
                ('attack', models.PositiveIntegerField(verbose_name='Ataque')),
                ('defense', models.PositiveIntegerField(verbose_name='Defensa')),
                ('special_attack', models.PositiveIntegerField(verbose_name='Ataque especial')),
                ('special_defense', models.PositiveIntegerField(verbose_name='Defensa especial')),
                ('speed', models.PositiveIntegerField(verbose_name='Velocidad')),
                ('is_legendary', models.BooleanField(default=False, verbose_name='¿Es legendario?')),
                ('is_mythical', models.BooleanField(default=False, verbose_name='¿Es mítico?')),
                ('generation', models.PositiveIntegerField(verbose_name='Generación')),
                ('sprite_default', models.URLField(verbose_name='Sprite frontal')),
                ('sprite_shiny', models.URLField(verbose_name='Sprite shiny frontal')),
                ('official_artwork_default', models.URLField(verbose_name='Artwork oficial')),
                ('official_artwork_shiny', models.URLField(blank=True, null=True, verbose_name='Artwork oficial shiny')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Pokémon',
                'verbose_name_plural': 'Pokémon',
                'ordering': ['pokedex_id'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='types/')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(blank=True, max_length=100, null=True, verbose_name='Condición de evolución')),
                ('level', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nivel requerido')),
                ('item', models.CharField(blank=True, max_length=100, null=True, verbose_name='Objeto requerido')),
                ('from_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolves_to', to='pokemon.pokemon', verbose_name='Evoluciona de')),
                ('to_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolves_from', to='pokemon.pokemon', verbose_name='Evoluciona a')),
            ],
            options={
                'verbose_name': 'Evolución',
                'verbose_name_plural': 'Evoluciones',
                'ordering': ['from_pokemon', 'to_pokemon'],
                'unique_together': {('from_pokemon', 'to_pokemon')},
            },
        ),
        migrations.CreateModel(
            name='PokemonAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='¿Es oculta?')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.ability')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='pokemon.pokemon')),
            ],
            options={
                'verbose_name': 'Habilidad de Pokémon',
                'verbose_name_plural': 'Habilidades de Pokémon',
                'ordering': ['pokemon', 'is_hidden'],
                'unique_together': {('pokemon', 'ability')},
            },
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveIntegerField(verbose_name='Slot (1 o 2)')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='pokemon.pokemon')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.type')),
            ],
            options={
                'verbose_name': 'Tipo de Pokémon',
                'verbose_name_plural': 'Tipos de Pokémon',
                'ordering': ['pokemon', 'slot'],
                'unique_together': {('pokemon', 'type', 'slot')},
            },
        ),
    ]
