# Generated by Django 5.2.1 on 2025-05-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='icon',
        ),
    ]
